version: '3.8'
services:
  app:
    image: 'node:18'
    container_name: app
    env_file:
      - ./.env
    volumes:
      - ./dist:/opt/app
      - ./node_modules:/opt/app/node_modules
    working_dir: /opt/app
    command: node app.js
    ports:
      - 9000:9000
    depends_on:
      data-source:
        condition: service_healthy

  data-source:
    image: 'postgres:latest'
    container_name: data-source
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db'
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s
      retries: 5
